### ISSUE TITLE
Runtime errors

### ISSUE THREAD

**Issue by subash774** [mcapllonch/SenseBackSim#1]
```bundle_2_nominalEC/anatomy.py``` in ```line 16``` tries to import ```planar as pl``` but I can't seem to find ```planar``` anywhere in the directory/module.

There was an error in ```line 14``` too for ```import triangle```, I solved that by replacing it with ```from geometry import Traingle as triangle```. 

Where can I find ```planar``` please?

Thanks!

**Comment by mcapllonch** [comment]
Hi @subash774 , the `triangle` package you need is not the class `Triangle` from `geometry`.
You can install both `planar` and `triangle` by doing `pip install planar triangle`. If you're not using `pip`, or want more information, you can find these packages here:

Triangle:
https://pypi.org/project/triangle/
https://github.com/drufat/triangle
Planar:
https://pypi.org/project/planar/

Thanks for your interest, and please let me know if the problem persists.

**Comment by subash774** [comment]
Ahhh I see, my bad, sorry.

May I suggest adding a ```requirements.txt``` file at the root directory listing all the pip packages used in the module? 

Thanks a lot!

**Comment by subash774** [comment]
@mcapllonch some errors I ran into. 

```SenseBackSim/publication_data/dataset_03__propagation/bundle_1_nominalEC/visualisation.py``` has a random ```df2``` floating around in line 424.

After that is solved, the script tries to access ```data/results/images``` folder which doesn't exist. Could probably do a simple ```Path("./data/results/images").mkdir(parents=True, exist_ok=True)``` so it creates the folder if it doesn't exist. 

These are simple errors, no worries. I'd create a pull request but I want to make sure everything runs first. I am not too sure about the following though.

There's NEURON error from ```src/hoc/axon_mye_MRG_COMPLETE.hoc``` in ```line 158: insert mrg_axnode``` where it says ```NEURON: mrg_axnode is not a MECHANISM```.

Thanks.

**Comment by mcapllonch** [comment]
Thanks @subash774 for raising these issues. Your comments are very helpful to sort out these things that got through unnoticed. I'll go in order:

- I'll definitely add a requirements file as soon as possible. 

- I have removed that intrusive line in `visualisation.py`.

- I have added the images folders. They went unnoticed by git since they were empty. 

- The NEURON error should be because you need to compile the MRG model first. There is a compiled version in the folder `x86_64`, but that won't work for everyone. I suggest you remove that folder, then to copy the MRG model from the folder `src/mod/MRG` into the root folder, and then run `nrnivmodl`. That should create a new folder with the compiled model. Let me know if that works for you. I'll remove this folder and add this to the instructions shortly.

**Comment by mcapllonch** [comment]
Just for the record, all points dealt with in this issue have been solved, so I'm closing it.
